"""`pdharness new <slug>`: a working starting point, not an empty file.

The scaffold builds a minimal playable patch with the idioms that prevent the
silent-patch failures (a control with a receive twin, initialised at load;
audio on), verifies it with pdverify, renders a demo, and leaves a README and
a field-log stub.  The agent edits from something that already passes.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

BUILD = '''"""{slug}: {description}

Built with pdbuild, verified with pdverify.  Run it:

    python build_{slug}.py            # build -> verify -> render the demo
    python build_{slug}.py --build-only

The loop is build -> render -> analyze -> iterate.  You cannot hear a patch by
reading it; `verify()` is where every claim about the sound becomes a check.
"""

from __future__ import annotations

import sys
from pathlib import Path

from pdbuild import Patch, surface
from pdverify import analyze, expect, verify, write_wav
from pdverify.render import RenderSpec, render
from pdverify import control

HERE = Path(__file__).resolve().parent
PATCH = HERE / "{slug}.pd"

# The surface: name -> (lo, hi, default).  Each control becomes a slider on the
# canvas that sends `<name>` and receives `<name>_ui`, so a human, a MIDI map and
# a headless test all drive the same receive.
DIALS = dict(pitch=(36, 84, 57), level=(0, 1, 0.3))


def build() -> Path:
    p = Patch(700, 420)
    y = 30
    handles = {{}}
    for name, (lo, hi, default) in DIALS.items():
        handles[name] = surface.control(p, name, "hsl", x=30, y=y, lo=lo, hi=hi, default=default,
                                        label=name.upper())
        y += 60

    # pitch (MIDI) -> Hz -> a sine; level -> a de-zippered gain; out.
    p.cursor(300, 30)
    rp = p.obj("r pitch"); mtof = p.obj("mtof"); osc = p.obj("osc~")
    p.chain(rp, mtof, osc)
    rl = p.obj("r level"); pk = p.obj("pack f 30"); ln = p.obj("line~")
    p.chain(rl, pk, ln)
    gain = p.obj("*~")
    p.link(osc, 0, gain, 0); p.link(ln, 0, gain, 1)
    dac = p.obj("dac~")
    p.link(gain, 0, dac, 0); p.link(gain, 0, dac, 1)

    p.save(PATCH)
    return PATCH


def verify_patch(path: Path) -> bool:
    """Every claim is a check.  Add one per feature as the instrument grows."""
    checks = []

    def check(label, ok, detail=""):
        checks.append(ok)
        print(("  ok   " if ok else "  FAIL ") + label + (f"  ({{detail}})" if detail else ""))

    # 1. the default state sounds, in tune, and clean
    card = verify(str(path), [expect.not_silent(), expect.no_clipping(), expect.finite(),
                              expect.note("A3", tol_cents=30)],
                  spec=RenderSpec(duration=2.0))
    check("default state: sounds, no clipping, A3", card.passed, card.report.summary())

    # 2. the PITCH control reaches the oscillator: drive the _ui receive like a hand would, and
    #    measure the window AFTER the move (a whole-render pitch of A3-then-E4 is not E4;
    #    see LESSONS "measure the thing that can move" and the startup window).
    card = verify(str(path), [expect.within(0.6, 2.0, expect.note("E4", tol_cents=30))],
                  spec=RenderSpec(duration=2.0, controls=tuple(control.send("pitch_ui", 64, at=0.2))))
    check("PITCH slider -> E4 after the move", card.passed, card.report.summary())

    # 3. LEVEL at 0 takes the sound away (a control, not a switch): compare the level with the
    #    slider at 0 against the default, rather than asking for absolute silence (the 30 ms
    #    ramp from the loadbang default still sounds).
    r0 = render(str(path), RenderSpec(duration=1.5, controls=tuple(control.send("level_ui", 0, at=0.0))))
    r1 = render(str(path), RenderSpec(duration=1.5))
    drop = analyze(r1.audio).rms_dbfs - analyze(r0.audio).rms_dbfs
    check("LEVEL 0 -> at least 20 dB quieter than the default", drop > 20, f"{{drop:.1f}} dB")

    ok = all(checks)
    print(f"{{sum(checks)}}/{{len(checks)}} checks", "-- VERIFIED" if ok else "-- NOT VERIFIED")
    return ok


def demo(path: Path) -> Path:
    r = render(str(path), RenderSpec(duration=6.0, controls=tuple(
        control.send("pitch_ui", 57, at=0.0) + control.send("pitch_ui", 64, at=2.0) + control.send("pitch_ui", 60, at=4.0))))
    out = write_wav(HERE / "{slug}_demo.wav", r.audio)
    print("demo ->", out, "|", analyze(r.audio).summary())
    return out


if __name__ == "__main__":
    path = build()
    print("built ->", path)
    if "--build-only" in sys.argv:
        sys.exit(0)
    if verify_patch(path) or "--demo" in sys.argv:
        demo(path)
'''

README = """# {slug}

{description}

| File | What |
|---|---|
| `build_{slug}.py` | builds, verifies and renders the demo |
| `{slug}.pd` | the instrument; opens in vanilla Pd |
| `{slug}_demo.wav` | the rendered demo (regenerated by the build) |

Controls: {controls}. Each is a slider on the canvas with a `<name>_ui`
receive, so a MIDI map or a test drives the same thing a hand does.
"""


def scaffold(slug: str, description: str, base: Path) -> dict:
    if not slug.replace("_", "").isalnum() or not slug[0].isalpha():
        raise ValueError("slug must be letters, digits and underscores, starting with a letter")
    d = base / "instruments" / slug
    d.mkdir(parents=True, exist_ok=True)
    build = d / f"build_{slug}.py"
    if build.exists():
        raise FileExistsError(build)
    build.write_text(BUILD.format(slug=slug, description=description.replace('"', "'")), encoding="utf-8")
    (d / "README.md").write_text(README.format(slug=slug, description=description,
                                               controls="PITCH, LEVEL"), encoding="utf-8")
    from . import knowledge
    logs = base / "field_tests"
    logs.mkdir(parents=True, exist_ok=True)
    log = logs / f"{_dt.date.today().isoformat()}_{slug}.md"
    if not log.exists():
        log.write_text(knowledge.read("field_test/LOG_TEMPLATE.md").replace("<slug>", slug), encoding="utf-8")
    return {"build_script": str(build), "readme": str(d / "README.md"), "field_log": str(log),
            "next": f"python {build}  (then edit build() and verify_patch() toward the description)"}
